### ISSUE TITLE
Give better example for hand-written script=

### ISSUE THREAD

**Issue by kentfredric** [travis-perl/helpers#28]
as per IRC:

1. Using weird parameters to `make` don't work
2. Blobs like this in `script:` give the wrong result.
```yaml
before_install:
  - eval $(curl https://travis-perl.github.io/init) --auto
script:
  - perl Makefile.PL
  - make
  - prove -lv $(test-dirs)
```
