### ISSUE TITLE
Document which dir to use for cache

### ISSUE THREAD

**Issue by oalders** [travis-perl/helpers#54]
It looks to me that if I want to cache installed modules I need to add:

```yaml
cache:
  directories:
    - ~/perl5
```

I couldn't find this in the docs.  If it's worth adding, I'm happy to create a PR.
